# Generated by Django 4.2.5 on 2024-01-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSettings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
