# Generated by Django 4.2.2 on 2023-06-29 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('accountSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedaccountbridge',
            options={'verbose_name_plural': 'Blocked Account Bridges'},
        ),
        migrations.AlterField(
            model_name='blockedaccountbridge',
            name='blockedAccountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='blockedaccountbridge',
            name='blockerAccountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to='accounts.account'),
        ),
        migrations.AlterUniqueTogether(
            name='blockedaccountbridge',
            unique_together={('blockerAccountID', 'blockedAccountID')},
        ),
    ]
