# Generated by Django 4.2.2 on 2023-06-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSettings', '0002_alter_blockedaccountbridge_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='phoneNum',
        ),
    ]
