# Generated by Django 4.2.5 on 2024-01-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_last_login'),
        ('accountSettings', '0002_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('accountID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('isVerified', models.BooleanField(default=0)),
                ('verificationToken', models.CharField(max_length=35, null=True)),
                ('hasContentFilterEnabled', models.BooleanField(default=0)),
                ('displayTheme', models.CharField(choices=[('0', 'Light'), ('1', 'Dark')], default='0', max_length=1)),
                ('is2FAEnabled', models.BooleanField(default=0)),
            ],
        ),
    ]
