# Generated by Django 4.2.2 on 2023-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSettings', '0003_remove_settings_phonenum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockedaccountbridge',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='blockedaccountbridge',
            constraint=models.UniqueConstraint(fields=('blockerAccountID', 'blockedAccountID'), name='unique blocked account'),
        ),
        migrations.AddConstraint(
            model_name='blockedaccountbridge',
            constraint=models.CheckConstraint(check=models.Q(('blockerAccountID_id', models.F('blockedAccountID_id')), _negated=True), name='different blocked accounts'),
        ),
    ]
