# Generated by Django 4.2.2 on 2023-07-09 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=255)),
                ('isDefault', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TagBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('tagID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tagbridge',
            constraint=models.UniqueConstraint(fields=('tagID', 'accountID'), name='tag_account_composite'),
        ),
    ]
