# /Site/docker-compose.yml

version: "3.8"

services:
  redis:
    image: redis:alpine
    platform: linux/arm64/v8
  backend:
    build: ./
    environment:
      - DB_HOST=host.docker.internal
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  frontend:
    build: ./meshapp
    volumes:
      - ./meshapp:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
