# Generated by Django 4.2.2 on 2023-07-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='accounts.account')),
                ('to_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='accounts.account')),
            ],
        ),
    ]
