# Generated by Django 4.1.7 on 2023-06-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('encryptedPass', models.CharField(max_length=255)),
                ('phoneNum', models.CharField(max_length=15)),
                ('displayTheme', models.CharField(choices=[('L', 'Light'), ('D', 'Dark')], default='L', max_length=1)),
                ('enabled2Factor', models.BooleanField(default=False)),
                ('isMentor', models.BooleanField(default=False)),
                ('isMentee', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
