# Generated by Django 4.2.2 on 2023-07-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('encryptedPass', models.BinaryField(editable=True, max_length=64)),
                ('salt', models.BinaryField(editable=True, max_length=36)),
                ('phoneNum', models.CharField(max_length=15)),
                ('displayTheme', models.CharField(choices=[('L', 'Light'), ('D', 'Dark')], default='L', max_length=1)),
                ('enabled2Factor', models.BooleanField(default=False)),
                ('isMentor', models.BooleanField(default=False)),
                ('isMentee', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
