# Generated by Django 4.2.2 on 2023-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('encryptedPass', models.CharField(max_length=64)),
                ('phoneNum', models.CharField(max_length=15)),
                ('isMentee', models.BooleanField()),
                ('isMentor', models.BooleanField()),
            ],
        ),
    ]
