# Generated by Django 4.2.2 on 2023-06-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salt',
            field=models.CharField(default='he', max_length=20),
            preserve_default=False,
        ),
    ]
