# Generated by Django 4.2.2 on 2023-06-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='salt',
        ),
    ]
