# Generated by Django 4.2.4 on 2023-09-29 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_groups_account_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_permissions",
        ),
    ]
