# Generated by Django 4.2.4 on 2024-04-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_account_displaytheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="otp_base32",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
