# Generated by Django 4.2.2 on 2023-06-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salt',
            field=models.CharField(default='he', max_length=36),
            preserve_default=False,
        ),
    ]
