# Generated by Django 4.2.4 on 2023-09-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_account_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="otp_base32",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
