# Generated by Django 4.2.4 on 2024-04-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_otp_base32"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="otp_base32",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
