# Generated by Django 4.2.4 on 2024-04-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_otp_base32"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is2FAEnabled",
            field=models.BooleanField(default=False),
        ),
    ]
