# Generated by Django 4.2.4 on 2023-09-29 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_logged_in_account_otp_base32"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="logged_in",
        ),
    ]
