# Generated by Django 4.1.13 on 2024-04-02 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_account_is2faenabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is2FAEnabled",
        ),
    ]
