# Generated by Django 4.2.2 on 2023-06-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_encryptedpass_alter_account_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='encryptedPass',
            field=models.BinaryField(editable=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='salt',
            field=models.BinaryField(editable=True, max_length=36),
        ),
    ]
