# Generated by Django 4.2.2 on 2023-06-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('encryptedPass', models.CharField(max_length=64)),
                ('displayTheme', models.CharField(choices=[('L', 'LIGHT'), ('D', 'DARK')], max_length=6)),
                ('phoneNum', models.CharField(max_length=15)),
                ('is2FAEnabled', models.BooleanField(default=False)),
                ('isMentee', models.BooleanField()),
                ('isMentor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.account')),
                ('userName', models.CharField(max_length=255)),
                ('preferredName', models.CharField(max_length=255, null=True)),
                ('preferredPronouns', models.CharField(max_length=40)),
            ],
        ),
    ]
