# Generated by Django 4.2.4 on 2023-08-14 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('occupationID', models.AutoField(primary_key=True, serialize=False)),
                ('occupationName', models.CharField(max_length=255)),
                ('occupationOrganization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupationStartDate', models.DateField(blank=True, null=True)),
                ('occupationEndDate', models.DateField(blank=True, null=True)),
                ('occupationDescription', models.TextField(blank=True, null=True)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('occupationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occupations.occupation')),
            ],
        ),
    ]
