# Generated by Django 4.2.2 on 2023-07-09 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('userName', models.CharField(max_length=255)),
                ('preferredName', models.CharField(max_length=255, null=True)),
                ('preferredPronouns', models.CharField(max_length=40)),
                ('biography', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
