# Generated by Django 4.2.2 on 2023-07-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.TimeField()),
                ('notificationContextJSON', models.JSONField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
