# Generated by Django 4.2.2 on 2023-07-09 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('educationID', models.AutoField(primary_key=True, serialize=False)),
                ('degreeName', models.CharField(max_length=255)),
                ('collegeName', models.CharField(max_length=255)),
                ('optionalDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationBridge',
            fields=[
                ('accountID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.profile')),
                ('educationID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.education')),
            ],
        ),
    ]
