# Generated by Django 4.2.4 on 2023-08-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('educationID', models.AutoField(primary_key=True, serialize=False)),
                ('degreeName', models.CharField(max_length=255)),
                ('collegeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EducationBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationStartDate', models.DateField(blank=True, null=True)),
                ('educationEndDate', models.DateField(blank=True, null=True)),
                ('educationDescription', models.TextField(blank=True, null=True)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('educationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.education')),
            ],
        ),
    ]
